### ISSUE TITLE
Air Code Loses Connection When Saving Large Files

### ISSUE THREAD

**Issue by GasGonky** [twolivesleft/codea-air-code#7]
When the file is larger than about 16k characters, vscode loses connection to the iPad for a split second as it tries to save.

***What I Know***
- Only the large file in question fails to save, other files in the project don't lose connection, provided that they are not large.
- Line returns are twice as costly as normal characters:
```lua
--[[###...###12345]]
```
and
```lua
--[[###...###123
]]
```
are both at the character limit.

- The character limit is effect by multiple factors:
  - The project's name
  - The file's name
  - The Main.lua file has a lower limit than other files with the same size name
  - It seems to be governed by the following:
    `character_limit = base_limit - #project_name - #file_name - is_main_offset`

***My Speculations***
_(As a non-expert who is familiar with neither vscode's API, or this repository.)_

My best guess is that the URI vscode sends to the iPad's server has a character limit, either on vscode's or IOS' side, probably about 16384 (2^14), given the proximity of the character limits I've seen (around 16290) and the 'niceness' of 2^14. This theory is further supported by my efforts to reconstruct part of the URI (which I'll admit is still quite incomplete):
```
codea://000.000.0.000:18513/Codea/AirCode Stress Test/Test1.lua#
```
Which accounts for a large part of the difference. (Although once again, this is all just speculation on my part)

***In Closing***

Thank you for taking the time to read this, and I'm sorry if this is was the wrong place to put it.

**Comment by jfperusse** [comment]
Hi @GasGonky! Thanks a lot for this detailed report. We'll definitely look into fixing this for the next update.

**Comment by jfperusse** [comment]
@GasGonky Thanks to your detailed post, it was very easy to find the source of the problem and you pretty much found the exact value which is the default limit for received messages in a vapor websocket server (see https://github.com/vapor/vapor/blob/e98077ddd1e3535bea6c9514f99d57463816c3bd/Sources/Vapor/Routing/RoutesBuilder%2BWebSocket.swift#L14).

The fix is thus very simple and I confirmed it works by allowing larger messages (1 << 20, so up to 1 MB). We have yet to finalize some major improvements to Air Code, but once done, this fix will be included.

Thanks again!

**Comment by GasGonky** [comment]
Thank you for looking into it so quickly!
